##===- projects/jssec/tools/jssec/Makefile ---------------*- Makefile -*-===##

#
# Indicate where we are relative to the top of the source tree.
#
LEVEL=../..

#
# Give the name of the tool.
#
TOOLNAME=JSSec

#
# List libraries that we'll need
# We use LIBS because jssec is a dynamic library.
#
USEDLIBS = jssec.a

LINK_COMPONENTS = all

#
# Include Makefile.common so we know what to do.
#
include $(LEVEL)/Makefile.common

